export default [
  "     2.11           OBSERVATION DATA    M (MIXED)           RINEX VERSION / TYPE",
  "TTS-4               NOVJ                20180626 23:59:42UTCPGM / RUN BY / DATE ",
  "NOVJ_ANT                                                    MARKER NAME         ",
  "1                                                           MARKER NUMBER       ",
  "URISOFT             NOVJ_SSTF                               OBSERVER / AGENCY   ",
  "0117                TTS-4               2.38 hw:133.32      REC # / TYPE / VERS ",
  "10180002            LEIAR25.R3 NONE                         ANT # / TYPE        ",
  "   452260.6174  3635872.0696  5203456.6948                  APPROX POSITION XYZ ",
  "        0.0000        0.0000        0.0000                  ANTENNA: DELTA H/E/N",
  "     1     1                                                WAVELENGTH FACT L1/2",
  "    14    L1    L2    L5    C1    C2    P1    P2    C5    D1# / TYPES OF OBSERV ",
  "          D2    D5    S1    S2    S5                        # / TYPES OF OBSERV ",
  "S1 is Carrier to Noise Ratio for P-code data on L1 [db*Hz]  COMMENT             ",
  "S2 is Carrier to Noise Ratio for P-code data on L2 [db*Hz]  COMMENT             ",
  "S5 is Carrier to Noise Ratio for P-code data on L5 [db*Hz]  COMMENT             ",
  "SNR [db*Hz] is mapped to RINEX snr flag value [1-9]         COMMENT             ",
  " <12 -> 1; 12-17 -> 2; 18-23 -> 3; 24-29 -> 4; 30-35 -> 5   COMMENT             ",
  " 36-41 -> 6; 42-47 -> 7; 48-53 -> 8; >54 -> 9               COMMENT             ",
  "CABLE AND INTERNAL DELAYS NOT APPLIED                       COMMENT             ",
  "    30.000                                                  INTERVAL            ",
  "  2018     6    27     0     0    0.0000000     GPS         TIME OF FIRST OBS   ",
  "                                                            END OF HEADER       "
];
